export enum NotificationCategory {
  MESSAGES = 'Messages',
  LIKES = 'Likes',
  ACTIONS = 'Actions',
}

export enum MessageType {
  RECEIVED_OFFER = 'RECEIVED_OFFER',
  OFFER_DECLINED_BY_MINIMUM = 'OFFER_DECLINED_BY_MINIMUM',
  RECEIVED_COUNTER_OFFER = 'RECEIVED_COUNTER_OFFER',
  OFFER_ACCEPTED = 'OFFER_ACCEPTED',
  OFFER_DECLINED = 'OFFER_DECLINED',
  COUNTER_OFFER_DECLINED = 'COUNTER_OFFER_DECLINED',
  OFFER_DONE = 'OFFER_DONE',
  RECEIVED_MESSAGE = 'RECEIVED_MESSAGE',
  FOLLOWING = 'FOLLOWING',
  ITEM_SHIPPED = 'ITEM_SHIPPED',
  ITEM_SOLD_AND_NEED_TO_SHIP = 'ITEM_SOLD_AND_NEED_TO_SHIP',

  ORDER_CREATED = 'CREATED',
  ORDER_PAID = 'PAID',
  PURCHASING_SHIPPING = 'PURCHASING_SHIPPING',
  ORDER_SHIPPING = 'SHIPPING',
  ORDER_SHIPPED = 'SHIPPED',
  ORDER_COMPLETED = 'COMPLETED',
  ORDER_REFUNDING = 'REFUNDING',
  ORDER_REFUNDED = 'REFUNDED',
  ORDER_RETURNED = 'RETURNED',
  ORDER_DECLINED = 'DECLINED',
  PACKAGE_EXPIRED = 'PACKAGE_EXPIRED',
}
