export enum SlideScreenType {
  BRAND = 'BRAND',
  CATEGORY = 'CATEGORY',
  CATEGORY_WITH_ATTRIBUTE = 'CATEGORY_WITH_ATTRIBUTE',
  PERSONAS = 'PERSONAS',
  KEYWORDS = 'KEYWORDS',
  SELLER = 'SELLER',
  PRODUCT_DETAIL = 'PRODUCT_DETAIL',
  BEST_SELLER = 'BEST_SELLER',
  NEW_ITEMS = 'NEW_ITEMS',
  HOT_DEAL = 'HOT_DEAL',
  FEED = 'FEED',
}
